### ISSUE TITLE
docker启动参数问题

### ISSUE THREAD

**Issue by chaoyuechen** [nianhua99/PandoraNext-Helper#1]
`-e PANDORA_NEXT_DOMAIN:<YOUR_PANDORA_NEXT_DOMAIN>`这里应该用等于符号
`-e PANDORA_NEXT_DOMAIN=<YOUR_PANDORA_NEXT_DOMAIN>`

`docker pull q11391/pandora-next-helper` 镜像需要一个latest的tag
https://hub.docker.com/r/q11391/pandora-next-helper/tags

**Comment by nianhua99** [comment]
不好意思，我会尽快处理

**Comment by nianhua99** [comment]
已推送 latest
