### ISSUE TITLE
setup密码强度不够，还有验证码是必须的吗

### ISSUE THREAD

**Issue by zhuxian89** [nianhua99/PandoraNext-Helper#10]
1.setup密码
本身PandoraNext的可以的，这里强度不够了

2.验证码：
app:check_require_config:141 - 不支持的验证码提供商

这个一定要配置吗？

**Comment by nianhua99** [comment]
1.setup密码强度的问题，今天会修复，会和PandoraNext保持一致的要求
2.验证码是必选配置的，你可以申请一个

**Comment by nianhua99** [comment]
setup password的问题已修复
验证码实在不想用可以设置一个hcaptcha提供的测试key，你在hcaptcha的官网可以找到
