### ISSUE TITLE
docker命令行启动helper后，容器不断重启

### ISSUE THREAD

**Issue by goldenhawksu** [nianhua99/PandoraNext-Helper#12]
pandoranext 用docker安装在"/root/pandoranext"目录，并且把config.json放在下面的data目录里，pandoranext访问没问题。

以下命令行启动helper后，容器不断重启，是哪里没写对吗？pandoranext_domain是我的VPS的域名。

docker run -d --restart=always --name PandoraNext-Helper --net=bridge \
    -p 8182:8182 \
    -v /root/pandoranext/data:/data \
    -e PANDORA_NEXT_DOMAIN="http://pandoranext_domain:8181" \
    q11391/pandora-next-helper

**Comment by nianhua99** [comment]
有无其他日志看下呢？或者使用python启动？

**Comment by goldenhawksu** [comment]
找到原因了
“”config.json文件，包括setup_password|captcha|proxy_api_prefix“ ， 这三个都必须设置，我原来没有设置setup_password和captcha, 现在齐活儿了，谢谢！
