### ISSUE TITLE
之前手动维护的share token可以同步过来吗

### ISSUE THREAD

**Issue by WorkHead** [nianhua99/PandoraNext-Helper#15]
之前没用这个工具，自己生成并在tokens.json里面手动维护的share token，可以直接同步过来管理吗

**Comment by nianhua99** [comment]
因为helper无法获取你token背后的账号/密码，所以没有办法直接导入原有的tokens.json

**Comment by nianhua99** [comment]
你可以在helper里手动新增一下，还按之前的uniquename，helper会帮你刷新一下，使用ShareToken的人是没有感知的
