### ISSUE TITLE
刷新会直接覆盖原因tokens.json内容

### ISSUE THREAD

**Issue by Feliks151450** [nianhua99/PandoraNext-Helper#16]
我一开始在tokens.json中配置了几个直接用rt登录的，用Helper创建几个用户后发现，tokens.json内容全部被Helper覆盖了。
建议刷新的时候先读取tokens.json的内容，只刷新特定的部分而不是全局覆盖。也可以在登录的时候读取tokens.json的内容，方便一起管理

**Comment by nianhua99** [comment]
感谢反馈，要想在初始化helper时保留之前的tokens.json，其实并不容易，因为tokens.json内的数据比较灵活。原来的计划是做一个初始页，在第一次使用helper时，帮助用户保存原来的tokens.json，但是开发成本较大，而且之前获取一个session token 成本并不高，所以搁置了这个计划。
helper优先级最高的计划还是 pool token管理，以及share token用量统计
我折中的开发了一个备份功能，每次刷新的时候会将原来的文件做个备份，这样也可以找回之前的数据，今晚就会发一个版本
为你造成的困扰敬请谅解

**Comment by Feliks151450** [comment]
> 感谢反馈，要想在初始化helper时保留之前的tokens.json，其实并不容易，因为tokens.json内的数据比较灵活。原来的计划是做一个初始页，在第一次使用helper时，帮助用户保存原来的tokens.json，但是开发成本较大，而且之前获取一个session token 成本并不高，所以搁置了这个计划。 helper优先级最高的计划还是 pool token管理，以及share token用量统计 我折中的开发了一个备份功能，每次刷新的时候会将原来的文件做个备份，这样也可以找回之前的数据，今晚就会发一个版本。同时会更新文档提醒用户。 为你造成的困扰敬请谅解

刚尝试了一下，可以在make_json函数里把`tokens={}`修改成以下代码:
```Python
    import os
    from flask import current_app
    users = query_db("select * from users")
    f = open(os.path.join(current_app.config['pandora_path'], 'tokens.json'), 'r')
    content = f.read()
    tokens = json.loads(content)
    f.close()
```
这样刷新时就只会刷新特定的token key，无关的token key会被保留下来

**Comment by nianhua99** [comment]
good，你要提一个pr吗？

**Comment by Feliks151450** [comment]
> good，你要提一个pr吗？

这么简单就不必了，你直接加到代码里就好了

**Comment by hcppxgit** [comment]
你好，请问一个很小白的问题，我看docker日志里面每分钟都在运行一次定时任务，这是正常的吗？为什么定时任务不是7天运行呢。INFO:apscheduler.scheduler:Added job "my_job" to job store "default"
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2023-12-25 21:55:01.548330+08:00 (in 59.992123 seconds)
DEBUG:apscheduler.scheduler:Looking for jobs to run
INFO:apscheduler.executors.default:Running job "my_job (trigger: interval[0:01:00], next run at: 2023-12-25 21:56:01 CST)" (scheduled at 2023-12-25 21:55:01.548330+08:00)
DEBUG:apscheduler.scheduler:Next wakeup is due at 2023-12-25 21:56:01.548330+08:00 (in 59.990284 seconds)
2023-12-25 21:55:01.825 | INFO     | pandora_tools:fresh_setup:17 - 重载：{'code': 0, 'detail': 'success'}
INFO:apscheduler.executors.default:Job "my_job (trigger: interval[0:01:00], next run at: 2023-12-25 21:56:01 CST)" executed successfully
DEBUG:apscheduler.scheduler:Looking for jobs to run
INFO:apscheduler.executors.default:Running job "my_job (trigger: interval[0:01:00], next run at: 2023-12-25 21:57:01 CST)" (scheduled at 2023-12-25 21:56:01.548330+08:00)
2023-12-25 21:56:01.566 | INFO     | pandora_tools:fresh_setup:17 - 重载：{'code': 0, 'detail': 'success'}
INFO:apscheduler.executors.default:Job "my_job (trigger: interval[0:01:00], next run at: 2023-12-25 21:57:01 CST)" executed successfully
DEBUG:apscheduler.scheduler:Next wakeup is due at 2023-12-25 21:57:01.548330+08:00 (in 59.978911 seconds)
DEBUG:apscheduler.scheduler:Looking for jobs to run
INFO:apscheduler.executors.default:Running job "my_job (trigger: interval[0:01:00], next run at: 2023-12-25 21:58:01 CST)" (scheduled at 2023-12-25 21:57:01.548330+08:00)
DEBUG:apscheduler.scheduler:Next wakeup is due at 2023-12-25 21:58:01.548330+08:00 (in 59.992023 seconds)
2023-12-25 21:57:01.580 | INFO     | pandora_tools:fresh_setup:17 - 重载：{'code': 0, 'detail': 'success'}
INFO:apscheduler.executors.default:Job "my_job (trigger: interval[0:01:00], next run at: 2023-12-25 21:58:01 CST)" executed successfully

**Comment by nianhua99** [comment]
> 你好，请问一个很小白的问题，我看docker日志里面每分钟都在运行一次定时任务，这是正常的吗？为什么定时任务不是7天运行呢。INFO:apscheduler.scheduler:Added job "my_job" to job store "default" DEBUG:apscheduler.scheduler:Looking for jobs to run DEBUG:apscheduler.scheduler:Next wakeup is due at 2023-12-25 21:55:01.548330+08:00 (in 59.992123 seconds) DEBUG:apscheduler.scheduler:Looking for jobs to run INFO:apscheduler.executors.default:Running job "my_job (trigger: interval[0:01:00], next run at: 2023-12-25 21:56:01 CST)" (scheduled at 2023-12-25 21:55:01.548330+08:00) DEBUG:apscheduler.scheduler:Next wakeup is due at 2023-12-25 21:56:01.548330+08:00 (in 59.990284 seconds) 2023-12-25 21:55:01.825 | INFO | pandora_tools:fresh_setup:17 - 重载：{'code': 0, 'detail': 'success'} INFO:apscheduler.executors.default:Job "my_job (trigger: interval[0:01:00], next run at: 2023-12-25 21:56:01 CST)" executed successfully DEBUG:apscheduler.scheduler:Looking for jobs to run INFO:apscheduler.executors.default:Running job "my_job (trigger: interval[0:01:00], next run at: 2023-12-25 21:57:01 CST)" (scheduled at 2023-12-25 21:56:01.548330+08:00) 2023-12-25 21:56:01.566 | INFO | pandora_tools:fresh_setup:17 - 重载：{'code': 0, 'detail': 'success'} INFO:apscheduler.executors.default:Job "my_job (trigger: interval[0:01:00], next run at: 2023-12-25 21:57:01 CST)" executed successfully DEBUG:apscheduler.scheduler:Next wakeup is due at 2023-12-25 21:57:01.548330+08:00 (in 59.978911 seconds) DEBUG:apscheduler.scheduler:Looking for jobs to run INFO:apscheduler.executors.default:Running job "my_job (trigger: interval[0:01:00], next run at: 2023-12-25 21:58:01 CST)" (scheduled at 2023-12-25 21:57:01.548330+08:00) DEBUG:apscheduler.scheduler:Next wakeup is due at 2023-12-25 21:58:01.548330+08:00 (in 59.992023 seconds) 2023-12-25 21:57:01.580 | INFO | pandora_tools:fresh_setup:17 - 重载：{'code': 0, 'detail': 'success'} INFO:apscheduler.executors.default:Job "my_job (trigger: interval[0:01:00], next run at: 2023-12-25 21:58:01 CST)" executed successfully

定时任务的逻辑，文档里说明有误，实际会每分钟检测一次token有没有失效，失效就会刷新，没有失效就不会刷新
