### ISSUE TITLE
添加共享用户时可否不填密码

### ISSUE THREAD

**Issue by WorkHead** [nianhua99/PandoraNext-Helper#19]
<img width="495" alt="image" src="https://github.com/nianhua99/PandoraNext-Helper/assets/7068530/48a79d82-c55b-44b4-b76e-2bcf4ed15e1b">
现在密码是必填的，但是我这边都是几个朋友间使用，设置密码有些繁琐了，可否放开这个限制

**Comment by nianhua99** [comment]
这是PandoraNext规定的，要么使用UniqueName+Password登录，要么用ShareToken登录，二选一的话肯定是UniqueName+Password方便些，而且账密不算麻烦，设置密码简单些即可

**Comment by WorkHead** [comment]
> 这是PandoraNext规定的，要么使用UniqueName+Password登录，要么用ShareToken登录，二选一的话肯定是UniqueName+Password方便些，而且账密不算麻烦，设置密码简单些即可

pandoraNext可以直接uniqueName不设密码登录的，之前我就一直没设置
