### ISSUE TITLE
【功能需求】能否增加一个针对share token管理的功能？

### ISSUE THREAD

**Issue by Tsenghan** [nianhua99/PandoraNext-Helper#2]
感谢开发者！能否增加一个针对share token管理的功能？
#### 1. 一个批量管理FK的页面
- **功能描述**：在一个表格中展示所有分发注册的FK，支持单独或批量操作。
- **表格显示内容**：
  | FK（前几位） | Access Token（后五位） | 有效期至| UniqueName（加星号） | 站点 | 限制？ | 隐藏用户信息？ |
  | ------------ | ----------------------- | ------ | --------------------- | ---- | ------ | -------------- |

#### 2. FK的操作按钮
- **更新**：更新选定FK的Access Token。
- **续期**：为FK续期，可指定时间。
- **吊销**：删除选定的FK。
- **查看详情**：查看FK的完整Access Token和UniqueName等信息。
- **导入Config文件**：将FK的配置信息导入pandoranext文件。
- **复制Share Token到剪切板**：方便快捷地复制Share Token。

#### 3. 多选FK后的按钮操作
- **一键更新**：批量更新选中的FK。
- **一键续期**：批量为选中的FK续期。
- **一键吊销**：批量删除选中的FK。
- **一键导入Config文件**：批量导入FK的配置信息。
- **组Pool Token**：将选中的多个FK组合成一个Pool Token。

#### 4. 通过Access Token生成FK
- **功能描述**：允许用户通过Access Token直接生成FK，并保存在FK列表中。
- **支持功能**：支持将多个UniqueName用逗号分隔，便于批量处理。

**Comment by nianhua99** [comment]
收到，你提到的很多功能系统已经实现了，你可能还没体验完系统的所有功能  
PandoraNext Helper的目的是对网站管理者屏蔽各种 Token 以及 Token 之间转换、生成的规则和操作。所以不打算提供各种直接操作Token的功能。
1. 关于Share Token的管理，我认为ShareToken与oai账号是紧密相关的，它不会脱离账号单独展示，你可以点击某行oai账号前面的 < 符号，它将展示这个账号下的所有ShareToken！
2. `更新` 和 `定时更新` 按钮会更新账号的 `Access Token`、`Session Token` 以及它下面的所有ShareToken！
3.  ShareToken的删除意思就是吊销此ShareToken
4. 系统使用了多种安全手段，保证系统只对管理员开放，所以我认为不需要对一些信息做脱敏处理。
5. 你提到的`导入`也已经实现！你可以点击`同步至PandoraNext`，它将刷新tokens.json文件，并且调用 PandoraNext的热重载功能
6. 通过Access Token生成FK，账号后面的`新增`按钮，会帮你做这个事情！
将要实现的功能：
1. 创建ShareToken时，开放更多的选项，如你所见，现在没有 站点限制、隐藏账号信息 等选项。
2. 对单个ShareToken 的管理，如续期，现在只有吊销
3. 针对Pool Token的管理
以上已经加入Todo！感谢你的总结！

**Comment by Tsenghan** [comment]
非常感谢将一些功能加入TODO，期待下一个版本

**Comment by zhuxindong** [comment]
搞个交流群吧大佬，热老的群消息太多了

**Comment by nianhua99** [comment]
> 搞个交流群吧大佬，热老的群消息太多了

在热佬群里聊=免费打广告👍
