### ISSUE TITLE
【功能建议】增加Fake Token 的自动刷新

### ISSUE THREAD

**Issue by DayDreammy** [nianhua99/PandoraNext-Helper#20]

**Comment by DayDreammy** [comment]
**Issue Description:**

**背景:**
在使用PandoraNext Helper过程中，我注意到项目的主要目标是方便地管理PandoraNext的Token，而对于使用Proxy的人来说，Fake Token在使用过程中可能会面临过期的情况。

**建议:**
我建议在项目中增加一个自动刷新Fake Token的功能，以确保用户可以持续使用这些Token而不需要手动干预。

**功能描述:**
具体而言，我建议在项目中实现一个定时任务或者后台进程，以在Fake Token即将过期时自动刷新它们。这样一来，用户就不必担心Token失效，提高了项目的用户友好性。

**可能的实现方式:**
一种可能的实现方式是在配置文件中设置Fake Token的有效期，并在到期前一定时间自动刷新。另一种方式是在每次使用Fake Token时检查其有效性，如果即将过期，则自动刷新。

**期望效果:**
通过增加自动刷新Fake Token的功能，可以提高用户体验，减少因Token失效而导致的操作中断，使PandoraNext Helper更加智能和方便。

**参考:**
这个建议的实现可以参考类似项目或其他Web应用中处理Token过期的做法，确保实现的安全可靠。

感谢您对项目的贡献，我相信这个功能将对提升PandoraNext Helper的实用性有很大的帮助。

**Comment by nianhua99** [comment]
你说的是ShareToken，Helper已经有自动刷新ShareToken的功能，另外不要用GPT提问
