### ISSUE TITLE
增加手动session token

### ISSUE THREAD

**Issue by SourceOnce** [nianhua99/PandoraNext-Helper#21]
chatgpt账号是谷歌登录的，手动f12获取的session token然后生成fk共享，希望加个不用登录，手填session token生成fk的功能

**Comment by nianhua99** [comment]
好提议，我会考虑这个，急用的话你现在可以将账号、密码、现在的session token手动插入到helper.db里，不过我还建议你用PandoraNext注册一个新账号

**Comment by nianhua99** [comment]
已实现，更新最新版本即可
