### ISSUE TITLE
群晖docker启动报错 app:check_require_config:102

### ISSUE THREAD

**Issue by zhoufxw** [nianhua99/PandoraNext-Helper#22]
在群晖6.2docker部署
存储空间：文件夹docker/pandoranext  装载路径/data
环境添加PANDORA_NEXT_DOMAIN="http://10.70.249.2:8181"
启动报错 2023-12-27 14:03:40.940 | ERROR    | app:check_require_config:102 - 请配置PandoraNext相关环境变量

**Comment by nianhua99** [comment]
发一下完整的启动命令

**Comment by zhoufxw** [comment]
![微信截图_20231227142732](https://github.com/nianhua99/PandoraNext-Helper/assets/43821103/54958059-144b-4b7d-830b-a346a52470c3)
![微信截图_20231227142723](https://github.com/nianhua99/PandoraNext-Helper/assets/43821103/03c13967-fbd0-4839-afa1-995bf0a9252b)
![微信截图_20231227142713](https://github.com/nianhua99/PandoraNext-Helper/assets/43821103/b51834a0-f64e-4edf-ab79-8f98740af006)

**Comment by zhoufxw** [comment]
```
 docker run -d --restart=always --name PandoraNext-Helper --net=host \
-v /volume1/docker/pandoranext:/data \
-e PANDORA_NEXT_DOMAIN="http://10.70.249.2:8181" \
q11391/pandora-next-helper
```

**Comment by nianhua99** [comment]
检查一下-v /volume1/docker/pandoranext 这个路径是你PandoraNext的路径吗，有没有config.json

**Comment by zhoufxw** [comment]
> 检查一下-v /volume1/docker/pandoranext 这个路径是你PandoraNext的路径吗，有没有config.json

搞定，需要映射config.json所在目录

**Comment by nianhua99** [comment]
没问题的话点个Star吧，感谢
