### ISSUE TITLE
增加功能：账号/密码里的密码可以手动修改更新

### ISSUE THREAD

**Issue by goldenhawksu** [nianhua99/PandoraNext-Helper#23]
有些拼车的plus账号, 会因为有人下车而变更密码；
pandoranext-helper里，已经输入的账号/密码没法修改，要改密码是不是需要删除重来？那下面的共享用户就没了.

**Comment by nianhua99** [comment]
感谢反馈，这个已经在做了，这两天就会更新！

**Comment by nianhua99** [comment]
单说拼车的话，还是建议使用ShareToken比较好

**Comment by LoEnzo** [comment]
添加用户的自定义token，第一次添加后后面能修改吗，比如最开始选择的session Token，添加完成后能修改为 refresh Token，
包括再次修改是否共享设置，貌似没有看到那里可以修改，大佬可以考虑是否添加此功能

**Comment by nianhua99** [comment]
> 添加用户的自定义token，第一次添加后后面能修改吗，比如最开始选择的session Token，添加完成后能修改为 refresh Token， 包括再次修改是否共享设置，貌似没有看到那里可以修改，大佬可以考虑是否添加此功能

目前没有这个计划，因为使用Helper后，SessionToken和RefreshToken都可以无限续期，Helper也是优先默认使用SessionToken，因为消耗额度低，所以我认为这样互相修改没有意义

**Comment by LoEnzo** [comment]
感谢回复，理解了，那另外一个是否考虑添加呢， 再次修改是否共享设置，目前好像只能删除后重新添加账户的时候首次设置

**Comment by nianhua99** [comment]
> 感谢回复，理解了，那另外一个是否考虑添加呢， 再次修改是否共享设置，目前好像只能删除后重新添加账户的时候首次设置

这个会做
