### ISSUE TITLE
使用HTTPS的Pandoranext会报错。

### ISSUE THREAD

**Issue by boy5260** [nianhua99/PandoraNext-Helper#26]
切换到了https，就报错了，具体信息是这样的：2023-12-28 08:40:24.430 | ERROR    | main.main:refresh:146 - HTTPSConnectionPool(host='XXXX', port=8181): Max retries exceeded with url: /spdb23423/api/auth/login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

请问这是哪里的问题啊？

**Comment by boy5260** [comment]
看提示是证书错误，但是我直接访问的话，证书是没问题的。

**Comment by nianhua99** [comment]
证书是自签名的吗，换成  http:// ip 试试？

**Comment by boy5260** [comment]
> 证书是自签名的吗，换成 http:// ip 试试？

是申请的腾讯免费证书，直接访问是正常的，没有证书报错。IP和域名我都试了，都一样

**Comment by hcppxgit** [comment]
应该是你服务器环境问题，我也是HTTPS，稳如老狗

**Comment by nianhua99** [comment]
我的https确实也正常，你试试把启动命令里的 `--net=bridge` 改为 `--net=host`，然后PANDORA_NEXT_DOMAIN 设置为 `http://127.0.0.1:8181`，看看行不行
