### ISSUE TITLE
执行flask db upgrade提示ERROR    | app:check_require_config:79 - 请配置proxy_api_prefix

### ISSUE THREAD

**Issue by lammy2021** [nianhua99/PandoraNext-Helper#28]
执行flask db upgrade提示ERROR    | app:check_require_config:79 - 请配置proxy_api_prefix
什么回事啊，我proxy_api_prefix留空不行吗，我填了一个url上去，再次运行还是不行啊。
这个是填代理服务器的吧

**Comment by muxinxy** [comment]
请注意前缀强度要求：不少于8位，且同时包含数字和字母！

**Comment by nianhua99** [comment]
proxy_api_prefix是 Pandoranext 规定的配置项，你必须开始 Proxy 模式，详情请查看 PandoraNext 文档

**Comment by nianhua99** [comment]
https://docs.pandoranext.com/zh-CN/configuration/config#proxy_api_prefix
