### ISSUE TITLE
更到最新进不去了

### ISSUE THREAD

**Issue by pretenderlu** [nianhua99/PandoraNext-Helper#29]
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

昨天部署完可用，今天更新后，login页面正常，输入密码后manage-users页面报错。

**Comment by nianhua99** [comment]
日志我看下

**Comment by pretenderlu** [comment]
> 日志我看下

我现在在外面玩，晚点回去了看看吧

**Comment by pretenderlu** [comment]
日志里反复出现的是这句：
no such column: users.refresh_token

**Comment by nianhua99** [comment]
新版本更新需要先执行 flask db upgrade

**Comment by nianhua99** [comment]
我在 release 里有说明

**Comment by pretenderlu** [comment]
> 我在 release 里有说明

原来如此，在外面玩就直接用portainer直接升了级，晚上重新弄一下。谢谢！
