### ISSUE TITLE
[功能建议]关于添加乘客功能的一点建议

### ISSUE THREAD

**Issue by hiBlunt** [nianhua99/PandoraNext-Helper#35]
增加乘客的时候，有两点建议：
1. 增加“备注”选项。使用场景：
1.1 时间久了很容易忘记乘客在其他交流软件上的昵称。那为什么不用其他IM上的昵称做token key呢？因为pandora next不能使用中文作为token key，我也很心塞
1.2 备注里写上用户到期时间，时间久了很容易忘记
2. 能否在乘客账户上添加“有效期”选项，并禁止过期账号登录

**Comment by nianhua99** [comment]
好提议，我会做这个

**Comment by nianhua99** [comment]
备注功能已更新

**Comment by nianhua99** [comment]
#39

**Comment by hiBlunt** [comment]
你好，备注功能确实更新了，但是已创建的用户就无法添加备注了吗？希望除了添加用户时，其他时候也可以修改备注
