### ISSUE TITLE
[bug]token刷新瞬间用户登录有报错

### ISSUE THREAD

**Issue by hiBlunt** [nianhua99/PandoraNext-Helper#37]
在token刷新的瞬间，用户登录，会显示“share token not found or expired”。在刷新完成后登录自动恢复。
可以在刷新token的函数中添加延迟，更容易复现此问题。
建议：
1.刷新token的任务放到晚上三点钟以后，在用户数量较低时执行此操作
2.能否找到彻底的解决方案？
感谢~

**Comment by nianhua99** [comment]
你是说在自动刷新的时候？还是点手动刷新？

**Comment by hiBlunt** [comment]
自动刷新。背景是用户反应登不上，报错：
![929493aee8b5c759a0f3151483abaa9](https://github.com/nianhua99/PandoraNext-Helper/assets/21240907/60414164-cd27-42bc-ad2b-3fc5aff4f722)
我查看发现在用户登录的1分钟之内token自动刷新了：
![image](https://github.com/nianhua99/PandoraNext-Helper/assets/21240907/91843232-cfd1-483a-8947-350e31e94cab)
，并且用户再次尝试登录，已经恢复正常。所以猜测是自动刷新的过程中旧token已失效，新token还未写入pandora，导致此现象发生。

**Comment by nianhua99** [comment]
这个应该是Access Token失效了，程序现在的自动刷新逻辑是每分钟检测1次Access Token是否失效，所以会有最多1分钟的不可用时间，而且触发条件比较苛刻，必须是Access Token失效的那一分钟，去使用ShareToken登录，才会触发

**Comment by hiBlunt** [comment]
看来是我运气不太好，，，恰好触发了小概率事件
记得之前access token的更新逻辑是定时5天刷新一次，这一块有更改吗？如果已知access token的有效期，在用户数量较少的时候，比如深夜，趁access token还未失效，主动去刷新access token，能否解决这个问题？

**Comment by nianhua99** [comment]
主要就是因为Access Token没办法预刷新，AccessToken没过期的时候去刷新，会返回之前的老Token，所以只能每分钟检测一下是否过期，过期了才刷，最开始那个逻辑有问题

**Comment by hiBlunt** [comment]
了解了，多谢，这个问题看来不太好解决:)

**Comment by hiBlunt** [comment]
看群里大佬说refresh token刷出来的access每次都给新的，这样能否解决问题？
