### ISSUE TITLE
用nginx代理后，同步至PandoraNext 按钮 和 刷新按钮 点击就失败问题

### ISSUE THREAD

**Issue by wuhaoyu010** [nianhua99/PandoraNext-Helper#38]
nginx代理设置如下
location ~ ^/www11111(/?)(.*)$ {
proxy_pass http://127.0.0.1:8182/www11111/$2;
}
添加用户 定时刷新 退出登录 删除按钮 点击不会报错
但同步至PandoraNext 按钮 点击后报错见下图2
刷新按钮 点击也一直失败
只有设置成如下这种形式才能成功，请帮忙检查下问题所在？tks
PS: 不用nginx 用服务器IP:8182这俩按钮点击也会报错
location /www11111/sync {
proxy_pass http://127.0.0.1:8182/www11111/sync;
}
![Snipaste_2024-01-04_16-15-16](https://github.com/nianhua99/PandoraNext-Helper/assets/25924081/073d87f9-09cf-46da-9f57-df0042401def)

![image](https://github.com/nianhua99/PandoraNext-Helper/assets/25924081/5cab517b-b5d4-446e-94bc-ae6dd711af77)

**Comment by nianhua99** [comment]
看下后端的日志
