### ISSUE TITLE
刷新失败

### ISSUE THREAD

**Issue by hcppxgit** [nianhua99/PandoraNext-Helper#4]
楼主你好，我添加账号后刷新失败，无法获取Session Token、Access Token，docker日志也没有错误消息`INFO:waitress:Serving on http://0.0.0.0:8182`，不知道问题出在哪了

**Comment by nianhua99** [comment]
你好，截图看一下，点刷新后没反应吗

**Comment by hcppxgit** [comment]
![2023-12-22-234642](https://github.com/nianhua99/PandoraNext-Helper/assets/22807140/adebd7ea-8772-4a19-85f2-8e6ba55b4d61)

**Comment by hcppxgit** [comment]
抱歉太晚了我得睡了，明晚下班我会再次尝试查找故障原因，到时候如有进展我会跟帖，谢谢。

**Comment by nianhua99** [comment]
建议你排查下：
1、账密是否正确
2、PandoraNext域名是否正确，刷新是去请求PandoraNext的Api
3、应该会有日志输出的

**Comment by hcppxgit** [comment]
`'“http://我的服务器IP/:8181/”/123.abcabc/api/auth/login'
2023-12-23 20:33:13.067 | ERROR    | main.main:refresh:111 - No connection adapters were found for '“http://我的服务器IP/:8181/”/123.abcabc/api/auth/login'`

我今天又重新拉了一下镜像再次部署，还是刷新失败，不过今天有如上日志了。


我的docker运行使用的代码是
`docker run -d --restart=always --name PandoraNext-Helper  \
    -p 8182:8182 \
    -v /pandoranext-deploy/data:/data \
    -e PANDORA_NEXT_DOMAIN=“http://我的服务器IP/:8181/” \
    q11391/pandora-next-helper:latest`


感觉是路径不对，我自己获取token使用的路径是`http://我的服务器IP:8181/123.abcabc/auth`，难道要把这个路径完整的填入docker的变量里面？

**Comment by hcppxgit** [comment]
卧槽，发出来我才感觉好像是docker变量那个IP地址后面多了个斜杠，我再去重新部署一次

**Comment by hcppxgit** [comment]
找到原因了，刷新成功了，问题出在环境变量上。代码应该
是`-e PANDORA_NEXT_DOMAIN=http://168.138.200.103:8181\`
而不是
`-e PANDORA_NEXT_DOMAIN=“http://168.138.200.103:8181/” \`或者`-e PANDORA_NEXT_DOMAIN=“http://168.138.200.103/:8181/” \`
应该是我之前是从浏览器复制过去的地址，端口号后面多了个左斜杠，导致地址组合错误。

**Comment by hcppxgit** [comment]
楼主我现在还有另外一个docker错误日志，这个日志是在我打开定时刷新按钮以后出现的：`2023-12-23 21:11:56.308 | INFO     | pandora_tools:fresh_setup:17 - 重载：{'code': 0, 'detail': 'success'}
ERROR:apscheduler.executors.default:Job "my_job (trigger: interval[0:01:00], next run at: 2023-12-23 21:18:10 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/main/main.py", line 149, in refresh_all_user
    users = query_db('select * from users')
  File "/app/app.py", line 79, in query_db
    cur = g.db.execute(query, args)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
ERROR:apscheduler.executors.default:Job "my_job (trigger: interval[0:01:00], next run at: 2023-12-23 21:19:10 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/main/main.py", line 149, in refresh_all_user
    users = query_db('select * from users')
  File "/app/app.py", line 79, in query_db
    cur = g.db.execute(query, args)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.`

**Comment by nianhua99** [comment]
定时bug已修复

> 楼主我现在还有另外一个docker错误日志，这个日志是在我打开定时刷新按钮以后出现的：`2023-12-23 21:11:56.308 | INFO | pandora_tools:fresh_setup:17 - 重载：{'code': 0, 'detail': 'success'} ERROR:apscheduler.executors.default:Job "my_job (trigger: interval[0:01:00], next run at: 2023-12-23 21:18:10 CST)" raised an exception Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job retval = job.func(*job.args, **job.kwargs) File "/app/main/main.py", line 149, in refresh_all_user users = query_db('select * from users') File "/app/app.py", line 79, in query_db cur = g.db.execute(query, args) File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in **get** obj = instance._get_current_object() File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object raise RuntimeError(unbound_message) from None RuntimeError: Working outside of application context.
> 
> This typically means that you attempted to use functionality that needed the current application. To solve this, set up an application context with app.app_context(). See the documentation for more information. ERROR:apscheduler.executors.default:Job "my_job (trigger: interval[0:01:00], next run at: 2023-12-23 21:19:10 CST)" raised an exception Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job retval = job.func(*job.args, **job.kwargs) File "/app/main/main.py", line 149, in refresh_all_user users = query_db('select * from users') File "/app/app.py", line 79, in query_db cur = g.db.execute(query, args) File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in **get** obj = instance._get_current_object() File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object raise RuntimeError(unbound_message) from None RuntimeError: Working outside of application context.
> 
> This typically means that you attempted to use functionality that needed the current application. To solve this, set up an application context with app.app_context(). See the documentation for more information.`
