### ISSUE TITLE
自动刷新没有成功

### ISSUE THREAD

**Issue by hcppxgit** [nianhua99/PandoraNext-Helper#41]
今天使用发现token过期，自动刷新没有按照预期成功运行，去后台看docker有如下日志`INFO:apscheduler.executors.default:Job "my_job (trigger: interval[0:01:00], next run at: 2024-01-06 14:51:01 CST)" executed successfully
DEBUG:apscheduler.scheduler:Looking for jobs to run
INFO:apscheduler.executors.default:Running job "my_job (trigger: interval[0:01:00], next run at: 2024-01-06 14:52:01 CST)" (scheduled at 2024-01-06 14:51:01.548330+08:00)
DEBUG:apscheduler.scheduler:Next wakeup is due at 2024-01-06 14:52:01.548330+08:00 (in 59.990603 seconds)
2024-01-06 14:51:01.560 | ERROR    | main.main:refresh_all_user:165 - 'user_id'
2024-01-06 14:51:01.560 | ERROR    | main.main:refresh_all_user:165 - 'user_id'
2024-01-06 14:51:01.561 | ERROR    | main.main:refresh_all_user:165 - 'user_id'
2024-01-06 14:51:01.561 | ERROR    | main.main:refresh_all_user:165 - 'user_id'
2024-01-06 14:51:01.561 | ERROR    | main.main:refresh_all_user:165 - 'user_id'
2024-01-06 14:51:01.576 | INFO     | pandora_tools:fresh_setup:17 - 重载：{'code': 0, 'detail': 'success'}
INFO:apscheduler.executors.default:Job "my_job (trigger: interval[0:01:00], next run at: 2024-01-06 14:52:01 CST)" executed successfully`
手动点击刷新按钮以后能正常刷新。

**Comment by nianhua99** [comment]
什么版本

**Comment by hcppxgit** [comment]
刚发现有新版本了，我是12月25号安装的，抱歉，今晚我会尝试重新安装新版本试试看。

**Comment by nianhua99** [comment]
好的，更新一下最新版本应该就好了

**Comment by hcppxgit** [comment]
感谢感谢

**Comment by DayDreammy** [comment]
> 今天使用发现token过期，自动刷新没有按照预期成功运行，去后台看docker有如下日志`INFO:apscheduler.executors.default:Job "my_job (trigger: interval[0:01:00], next run at: 2024-01-06 14:51:01 CST)" executed successfully DEBUG:apscheduler.scheduler:Looking for jobs to run INFO:apscheduler.executors.default:Running job "my_job (trigger: interval[0:01:00], next run at: 2024-01-06 14:52:01 CST)" (scheduled at 2024-01-06 14:51:01.548330+08:00) DEBUG:apscheduler.scheduler:Next wakeup is due at 2024-01-06 14:52:01.548330+08:00 (in 59.990603 seconds) 2024-01-06 14:51:01.560 | ERROR | main.main:refresh_all_user:165 - 'user_id' 2024-01-06 14:51:01.560 | ERROR | main.main:refresh_all_user:165 - 'user_id' 2024-01-06 14:51:01.561 | ERROR | main.main:refresh_all_user:165 - 'user_id' 2024-01-06 14:51:01.561 | ERROR | main.main:refresh_all_user:165 - 'user_id' 2024-01-06 14:51:01.561 | ERROR | main.main:refresh_all_user:165 - 'user_id' 2024-01-06 14:51:01.576 | INFO | pandora_tools:fresh_setup:17 - 重载：{'code': 0, 'detail': 'success'} INFO:apscheduler.executors.default:Job "my_job (trigger: interval[0:01:00], next run at: 2024-01-06 14:52:01 CST)" executed successfully` 手动点击刷新按钮以后能正常刷新。

+1

**Comment by nianhua99** [comment]
> > 今天使用发现token过期，自动刷新没有按照预期成功运行，去后台看docker有如下日志`INFO:apscheduler.executors.default:Job "my_job (trigger: interval[0:01:00], next run at: 2024-01-06 14:51:01 CST)" executed successfully DEBUG:apscheduler.scheduler:Looking for jobs to run INFO:apscheduler.executors.default:Running job "my_job (trigger: interval[0:01:00], next run at: 2024-01-06 14:52:01 CST)" (scheduled at 2024-01-06 14:51:01.548330+08:00) DEBUG:apscheduler.scheduler:Next wakeup is due at 2024-01-06 14:52:01.548330+08:00 (in 59.990603 seconds) 2024-01-06 14:51:01.560 | ERROR | main.main:refresh_all_user:165 - 'user_id' 2024-01-06 14:51:01.560 | ERROR | main.main:refresh_all_user:165 - 'user_id' 2024-01-06 14:51:01.561 | ERROR | main.main:refresh_all_user:165 - 'user_id' 2024-01-06 14:51:01.561 | ERROR | main.main:refresh_all_user:165 - 'user_id' 2024-01-06 14:51:01.561 | ERROR | main.main:refresh_all_user:165 - 'user_id' 2024-01-06 14:51:01.576 | INFO | pandora_tools:fresh_setup:17 - 重载：{'code': 0, 'detail': 'success'} INFO:apscheduler.executors.default:Job "my_job (trigger: interval[0:01:00], next run at: 2024-01-06 14:52:01 CST)" executed successfully` 手动点击刷新按钮以后能正常刷新。
> 
> +1

更新版本
