### ISSUE TITLE
群晖部署报错

### ISSUE THREAD

**Issue by zhuiyue132** [nianhua99/PandoraNext-Helper#42]
![image](https://github.com/nianhua99/PandoraNext-Helper/assets/26954775/b96f6d65-6631-4e55-8817-2f398d6825c8)
以下为yaml配置：
![image](https://github.com/nianhua99/PandoraNext-Helper/assets/26954775/194d5836-fdab-44ec-9b85-2c9c0140777f)
以下为全部日志：
[pandora-next-helper.zip](https://github.com/nianhua99/PandoraNext-Helper/files/13850476/pandora-next-helper.zip)

**Comment by nianhua99** [comment]
你的config.json应该有格式问题
