### ISSUE TITLE
共享和建议

### ISSUE THREAD

**Issue by hqzh** [nianhua99/PandoraNext-Helper#43]
![image](https://github.com/nianhua99/PandoraNext-Helper/assets/26128706/7f5a4d6b-8092-4733-bf5d-8d8ca2680196)
请问一下这个共享打勾是干嘛得呀？
那个密码是不是默认*******会好一点，边上有个类似于眼睛得开关

**Comment by hqzh** [comment]
![image](https://github.com/nianhua99/PandoraNext-Helper/assets/26128706/9e2930a5-ddac-41b8-8d66-14c96b325b26)

为啥我的用量按钮是灰色的。点击导出聊天也没反应

**Comment by nianhua99** [comment]
共享按钮对应Shared属性，打钩后会出现在Shared.html页面，详情查看PandoraNext文档
用量按钮，你车上没乘客自然是不能点击的，先新增几个乘客，才能看用量，导出聊天是导出到你邮箱里

**Comment by hqzh** [comment]
@nianhua99 我潘多拉本来就设置了Shared.html页面，那么勾选你这个就是假如潘多拉那边没有开启这个页面，你这个修改配置给开启？
