### ISSUE TITLE
一堆不支持的验证码提供商报错

### ISSUE THREAD

**Issue by shentong0722** [nianhua99/PandoraNext-Helper#48]
![image](https://github.com/nianhua99/PandoraNext-Helper/assets/63089521/0fe7aac0-7efb-4b6e-a1db-7bf75d4b53d9)
按照步骤docker刚部署完就一堆不支持的验证码提供商报错，然后8182端口也打不开
![image](https://github.com/nianhua99/PandoraNext-Helper/assets/63089521/5c595816-419c-4f01-8f32-11514605ded9)

**Comment by selor07** [comment]
我也遇到类似的问题，不知道如何解决

**Comment by nianhua99** [comment]
> ![image](https://private-user-images.githubusercontent.com/63089521/294972951-0fe7aac0-7efb-4b6e-a1db-7bf75d4b53d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTcyNjcsIm5iZiI6MTcwNDc5Njk2NywicGF0aCI6Ii82MzA4OTUyMS8yOTQ5NzI5NTEtMGZlN2FhYzAtN2VmYi00YjZlLWExZGItN2JmNzVkNGI1M2Q5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEwNDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3YTY0NWY5ZTI1ZmFkODc0ZmMzZjM2ZTRjZjMzM2RhN2MzOTczNmQ1MzljZjMyYTRlZTdhODc0NTQ1NGRhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hPSeVMD0-6rZTdbvJNNW200dwUixf6HOLse9oiBzyuY) 按照步骤docker刚部署完就一堆不支持的验证码提供商报错，然后8182端口也打不开 ![image](https://private-user-images.githubusercontent.com/63089521/294973609-5c595816-419c-4f01-8f32-11514605ded9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTcyNjcsIm5iZiI6MTcwNDc5Njk2NywicGF0aCI6Ii82MzA4OTUyMS8yOTQ5NzM2MDktNWM1OTU4MTYtNDE5Yy00ZjAxLThmMzItMTE1MTQ2MDVkZWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEwNDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0OWYxYzgyMGI3NmNjNGZkMmVhMmViMTI5ZDU0NTg0MzQzYWE2ZDQyNDgxMmE3NjJjZjc4NmVjYTUyZWM5MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UYksXOK0rexWFyn-lhOUazbSKmGxQ_HBgiWsuIyVric)



> 我也遇到类似的问题，不知道如何解决

更换 Hcaptcha，项目的readme有写

**Comment by nianhua99** [comment]
更换 Hcaptcha，项目的readme有写
@shentong0722 你的图片里有敏感信息，帮你删掉了
