### ISSUE TITLE
点击登录一直在等待

### ISSUE THREAD

**Issue by oneCatZz** [nianhua99/PandoraNext-Helper#49]
![CleanShot 2024-01-11 at 14 34 47@2x](https://github.com/nianhua99/PandoraNext-Helper/assets/32626686/a7ba61a7-d84b-42b0-9c10-ffff882bcebc)
如图所示，点击之后一直在等待，请问这个是什么原因，看docker日志也没有打印

**Comment by oneCatZz** [comment]
等待了一段时间之后报了个500，看了一下日志如下
![CleanShot 2024-01-11 at 14 46 10@2x](https://github.com/nianhua99/PandoraNext-Helper/assets/32626686/db28c97c-8046-4020-9996-765b4c01ffdb)

**Comment by nianhua99** [comment]
机器到hcaptcha网络不通，我周末会发新版本，到时候会放开验证码的限制

**Comment by HartleyLau** [comment]
和层主一样的问题，一直卡在hcaptcha这里，希望能够移除该限制

**Comment by Saktawdi** [comment]
催更😍

**Comment by nbb2025** [comment]
一样的问题，国内机器访问不了hcapture，用clash又会被ban，上次签了承诺书才给我vps解封

**Comment by HartleyLau** [comment]
> 一样的问题，国内机器访问不了hcapture，用clash又会被ban，上次签了承诺书才给我vps解封

可以通过手动将auth/auth.py文件和templates/login.html中的验证码相关逻辑移除即可，移除后可以正常登录访问使用。

**Comment by nianhua99** [comment]
新版本验证码是可选的了，网络不通的可以关闭验证码
