### ISSUE TITLE
为什么提示 setup password 强度不足啊

### ISSUE THREAD

**Issue by Feliks151450** [nianhua99/PandoraNext-Helper#5]
这个 helper 是对密码强度有很严格的要求吗。我密码符合 PandoraNext 里的要求的

**Comment by nianhua99** [comment]
这个我写成了字母+数字+符号，实际应该和 Pandora next 里保持一致，字母数字即可，这个我明天会修复下

**Comment by Feliks151450** [comment]
> 这个我写成了字母+数字+符号，实际应该和 Pandora next 里保持一致，字母数字即可，这个我明天会修复下

好的感谢，另外还有一个问题是验证码这部分必须有吗

**Comment by nianhua99** [comment]
> > 这个我写成了字母+数字+符号，实际应该和 Pandora next 里保持一致，字母数字即可，这个我明天会修复下
> 
> 好的感谢，另外还有一个问题是验证码这部分必须有吗

是的，验证码是必须的

**Comment by nianhua99** [comment]
已修复
验证码实在不想用，可以使用hcaptcha的测试key，你可以在他官网文档中找到
