### ISSUE TITLE
刷新失败

### ISSUE THREAD

**Issue by leichaoL** [nianhua99/PandoraNext-Helper#50]
添加账号之后刷新失败，根据 #4 检查了 账号密码和潘多拉地址都没有问题。
![image](https://github.com/nianhua99/PandoraNext-Helper/assets/66906588/17b0594e-e323-4017-ac9d-0beeeaa0699a)

报错代码是
`| ERROR    | main.main:refresh:218 - HTTPConnectionPool(host='0.0.0.0', port=8181): Max retries exceeded with url: /1z2x3c4v/api/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EB2C549890>: Failed to establish a new connection: [WinError 10049] 在其上下文中，该请求的地址无效。'))`

**Comment by nianhua99** [comment]
PANDORA_NEXT_DOMAIN 换成具体的IP或者域名
