### ISSUE TITLE
如何关闭验证码？

### ISSUE THREAD

**Issue by anonymous4me** [nianhua99/PandoraNext-Helper#52]
看大佬说周末更新代码，关闭验证码的强制开关
想关闭验证码，大佬给提示下如何关闭，谢谢
看大佬的代码更新了，我就用docker重新部署了，没发现什么变化
是docker镜像还没有更新吗？
我是用docker部署的
希望得到解答，谢谢

**Comment by lddcc** [comment]
镜像还没更新，等大佬更

**Comment by hqzh** [comment]
看他发了一个0.7.0，用不了

**Comment by nianhua99** [comment]
0.7.0 是Pre-Release版本，没有打包latest，需要指定一下版本号
