### ISSUE TITLE
docker报错RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by sgr997** [nianhua99/PandoraNext-Helper#54]
Traceback (most recent call last):
  File "/usr/local/bin/waitress-serve", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/waitress/runner.py", line 283, in run
    app = resolve(module, obj_name)
  File "/usr/local/lib/python3.9/site-packages/waitress/runner.py", line 218, in resolve
    obj = __import__(module_name, fromlist=segments[:1])
  File "/app/app.py", line 118, in <module>
    scheduler.start()
  File "/usr/local/lib/python3.9/site-packages/flask_apscheduler/scheduler.py", line 103, in start
    self._scheduler.start(paused=paused)
  File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/background.py", line 38, in start
    self._thread.start()
  File "/usr/local/lib/python3.9/threading.py", line 899, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by sgr997** [comment]
latest版本也报这个错，服务器是
`Linux VM-4-10-centos 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by nianhua99** [comment]
docker 什么版本

**Comment by xiaohuangtx** [comment]
我也遇到了这个问题

Docker version 20.10.6, build 370c289

Linux VM-8-6-centos 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

报错：
2024-01-15 19:15:45.345 | WARNING | app:check_require_config:92 - 未检测到hcaptcha验证码配置，建议您开启验证码 Traceback (most recent call last): File "/usr/local/bin/waitress-serve", line 8, in <module> sys.exit(run()) File "/usr/local/lib/python3.9/site-packages/waitress/runner.py", line 283, in run app = resolve(module, obj_name) File "/usr/local/lib/python3.9/site-packages/waitress/runner.py", line 218, in resolve obj = __import__(module_name, fromlist=segments[:1]) File "/app/app.py", line 118, in <module> scheduler.start() File "/usr/local/lib/python3.9/site-packages/flask_apscheduler/scheduler.py", line 103, in start self._scheduler.start(paused=paused) File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/background.py", line 38, in start self._thread.start() File "/usr/local/lib/python3.9/threading.py", line 899, in start _start_new_thread(self._bootstrap, ()) RuntimeError: can't start new thread

**Comment by sgr997** [comment]
> docker 什么版本

@nianhua99 应该是dockerfile的FROM有些问题，我自己找了个python3.9的镜像作为FROM基础镜像，build后在服务器部署没问题，但我找这个太大了，build完后有 700MB
<img width="305" alt="image" src="https://github.com/nianhua99/PandoraNext-Helper/assets/51942582/57c18fb9-c485-4ab4-a04a-b1519d7ee563">

**Comment by nianhua99** [comment]
> > docker 什么版本
> 
> @nianhua99 应该是dockerfile的FROM有些问题，我自己找了个python3.9的镜像作为FROM基础镜像，build后在服务器部署没问题，但我找这个太大了，build完后有 700MB <img alt="image" width="305" src="https://private-user-images.githubusercontent.com/51942582/297075431-57c18fb9-c485-4ab4-a04a-b1519d7ee563.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODIyNzYsIm5iZiI6MTcwNTQ4MTk3NiwicGF0aCI6Ii81MTk0MjU4Mi8yOTcwNzU0MzEtNTdjMThmYjktYzQ4NS00YWI0LWEwNGEtYjE1MTlkN2VlNTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA4NTkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNjA2ZTBiNWI5ZGIzMzlmMzViZTFmMzU3ZTliYTE4YjRiY2QyNjhlYTYzYjQ0ZjYzNWJjODAxZWUxN2I5NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P08aLEUOTGzB3pm5bvmn9z1KnhIZ6o5rvqgAEcD_0S4">

试下 python:3.9-slim-bullseye 作为基础镜像

**Comment by daomengRen** [comment]
> > docker 什么版本
> 
> @nianhua99 应该是dockerfile的FROM有些问题，我自己找了个python3.9的镜像作为FROM基础镜像，build后在服务器部署没问题，但我找这个太大了，build完后有 700MB <img alt="image" width="305" src="https://private-user-images.githubusercontent.com/51942582/297075431-57c18fb9-c485-4ab4-a04a-b1519d7ee563.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTc1MjEsIm5iZiI6MTcwNTU1NzIyMSwicGF0aCI6Ii81MTk0MjU4Mi8yOTcwNzU0MzEtNTdjMThmYjktYzQ4NS00YWI0LWEwNGEtYjE1MTlkN2VlNTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA1NTM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMzg5Yjk1YjUxODczMTUyMWViZWUwODVmYWFkYTc2YTdlOTkzYzUwYzM0YTNjMWIyYmFjN2NhNGM2ZWNiZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xKcUlKz184GhA7rwadSgZo4eYO5KjCfjrqeEZ6qObfA">

我也有这个问题，docker版本19.03.14，求大佬分享新的docker 镜像

**Comment by sgr997** [comment]
> > > docker 什么版本
> > 
> > 
> > @nianhua99 应该是dockerfile的FROM有些问题，我自己找了个python3.9的镜像作为FROM基础镜像，build后在服务器部署没问题，但我找这个太大了，build完后有 700MB <img alt="image" width="305" src="https://private-user-images.githubusercontent.com/51942582/297075431-57c18fb9-c485-4ab4-a04a-b1519d7ee563.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODIyNzYsIm5iZiI6MTcwNTQ4MTk3NiwicGF0aCI6Ii81MTk0MjU4Mi8yOTcwNzU0MzEtNTdjMThmYjktYzQ4NS00YWI0LWEwNGEtYjE1MTlkN2VlNTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA4NTkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNjA2ZTBiNWI5ZGIzMzlmMzViZTFmMzU3ZTliYTE4YjRiY2QyNjhlYTYzYjQ0ZjYzNWJjODAxZWUxN2I5NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P08aLEUOTGzB3pm5bvmn9z1KnhIZ6o5rvqgAEcD_0S4">
> 
> 试下 python:3.9-slim-bullseye 作为基础镜像

这个我在我本地打包试的也是不行
我本地系统是macos 13.5.1，Docker version 20.10.17

**Comment by daomengRen** [comment]
> > > > docker 什么版本
> > > 
> > > 
> > > @nianhua99 应该是dockerfile的FROM有些问题，我自己找了个python3.9的镜像作为FROM基础镜像，build后在服务器部署没问题，但我找这个太大了，build完后有 700MB <img alt="image" width="305" src="https://private-user-images.githubusercontent.com/51942582/297075431-57c18fb9-c485-4ab4-a04a-b1519d7ee563.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTc1MjEsIm5iZiI6MTcwNTU1NzIyMSwicGF0aCI6Ii81MTk0MjU4Mi8yOTcwNzU0MzEtNTdjMThmYjktYzQ4NS00YWI0LWEwNGEtYjE1MTlkN2VlNTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA1NTM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMzg5Yjk1YjUxODczMTUyMWViZWUwODVmYWFkYTc2YTdlOTkzYzUwYzM0YTNjMWIyYmFjN2NhNGM2ZWNiZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xKcUlKz184GhA7rwadSgZo4eYO5KjCfjrqeEZ6qObfA">
> > 
> > 
> > 我也有这个问题，docker版本19.03.14，求大佬分享新的docker 镜像
> 
> 试试能拉到吗 `docker run -d --restart=always --name PandoraNext-Helper --net=bridge -p 8182:8182 -v <YOUR_PANDORA_NEXT_PATH>:/data -e PANDORA_NEXT_DOMAIN="<YOUR_PANDORA_NEXT_DOMAIN>" registry.cn-hangzhou.aliyuncs.com/zxp_learn/helper:v0.7.0_rc1`

谢谢大佬，这个成功运行了
