### ISSUE TITLE
建议账号管理增加一个plus的checkbox

### ISSUE THREAD

**Issue by nbb2025** [nianhua99/PandoraNext-Helper#55]
建议账号管理增加一个plus的checkbox，每次刷新完都要找到对应的账号再手动去改token配置文件再重启pandora next。新版界面还真挺好看的，但也建议屏蔽掉未生效的按钮

**Comment by nianhua99** [comment]
这个可以有，那个未生效的按钮具体是指？

**Comment by nbb2025** [comment]
> 这个可以有，那个未生效的按钮具体是指？

点击头像-“仪表”，“个人资料”，”账户“会404
另外如果可以新增一个直接在helper里修改token.json和手动重启PandoraNext的按钮就好了
感谢作者大大用爱发电

**Comment by nianhua99** [comment]
> > 这个可以有，那个未生效的按钮具体是指？
> 
> 点击头像-“仪表”，“个人资料”，”账户“会404 另外如果可以新增一个直接在helper里修改token.json和手动重启PandoraNext就好了 感谢作者大大用爱发电

这个我下个版本去掉
