### ISSUE TITLE
0.7.0不设置验证码部署后，登陆页面无法访问。

### ISSUE THREAD

**Issue by Huangbingxiao** [nianhua99/PandoraNext-Helper#57]
登陆页面报错Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by Huangbingxiao** [comment]
补充: 访问地址为  ip地址:8182/proxyPrefix/login

**Comment by oneCatZz** [comment]
看readme，现在最新的版本只要ip和端口号了

**Comment by nianhua99** [comment]
直接使用IP端口访问，不用带 prefix了

**Comment by Huangbingxiao** [comment]
感谢支持，建议在READ.md中加粗。

**Comment by Huangbingxiao** [comment]
另外，是不是说明不再使用proxy_api_prefix了。【本项目复用了PandoraNext的config.json文件，包括setup_password|captcha|proxy_api_prefix】是不是表达有误。

**Comment by nianhua99** [comment]
> 另外，是不是说明不再使用proxy_api_prefix了。【本项目复用了PandoraNext的config.json文件，包括setup_password|captcha|proxy_api_prefix】是不是表达有误。

不冲突，helper会调用你的Pandoranext的很多API，所以复用proxy_api_prefix是必须得

**Comment by Huangbingxiao** [comment]
另外，现在我打开了登陆页面，输入密码登录没反应，docker logs查看，也并没有收到请求

**Comment by Huangbingxiao** [comment]
忘记说了，我没有配置验证码，腾讯云服务器访问hcapcha不通。
