### ISSUE TITLE
新注册的账号没有gtp store正常吗？

### ISSUE THREAD

**Issue by liqiujiong** [nianhua99/PandoraNext-Helper#61]
这个是搭别人的车的：
![image](https://github.com/nianhua99/PandoraNext-Helper/assets/5794205/d9620f50-17e6-468d-9a4f-e96ed9b85035)
gong'n'qi'quan功能齐全，
这个是我自己搭Pandora-next注册了个账号进去：
![image](https://github.com/nianhua99/PandoraNext-Helper/assets/5794205/0984a351-0363-4ca4-870c-f99251b3294b)

**Comment by nianhua99** [comment]
人家是Plus，你注册的只有3.5，肯定没gpts
