### ISSUE TITLE
不懂就问  添加完账号额度光速消耗完

### ISSUE THREAD

**Issue by Czj-9527** [nianhua99/PandoraNext-Helper#63]
![微信图片_20240120002312](https://github.com/nianhua99/PandoraNext-Helper/assets/56945877/c9425def-702f-4a71-830f-894bae896453)
如图  添加了4个账号  额度没了
proxy_api_prefix是新设置了  排除被刷的可能

**Comment by AndersonGhost** [comment]
情况跟你差不多，刚添加完6个账号，什么都没有做（没有问gpt任何问题），就消耗了2700点。
![image](https://github.com/nianhua99/PandoraNext-Helper/assets/33820659/27e1be90-1d15-4bee-a3b8-b4e4a85ea15b)

**Comment by nianhua99** [comment]
新增账号默认使用Refresh Token模式，一次1000额度，PandoraNext文档中有写，另外这两天登录接口也不稳定，即使失败也是会扣额度的。
详情看吾皇的文档https://docs.pandoranext.com/zh-CN/api-reference/proxy#%E9%A2%9D%E5%BA%A6%E6%B6%88%E8%80%97

**Comment by nianhua99** [comment]
如果怀疑调用逻辑有bug的话，可以看下后台日志，看下调用情况是不是有问题
