### ISSUE TITLE
gpt账号带特殊符号，helper会崩溃

### ISSUE THREAD

**Issue by hdhd3** [nianhua99/PandoraNext-Helper#7]
比如这种：7Xw%#ak!pOkIUyh5MOFq
只有去数据库把这个号删除了才正常

**Comment by nianhua99** [comment]
今天下午我会尽快修复，感谢反馈

**Comment by nianhua99** [comment]
已修复

**Comment by hdhd3** [comment]
最新的0.6.5版本中，账号有特殊符号的话又会显示500，数据库删除后才能进...

**Comment by nianhua99** [comment]
我这刚刚试了下是可以的，看看日志

**Comment by nianhua99** [comment]
![76f6c1628020c54d19ac5d596fe83ebb](https://github.com/nianhua99/PandoraNext-Helper/assets/48168645/71244061-df9c-4228-b970-e919a243939c)

**Comment by hdhd3** [comment]
重新添加了账号，正常了...之前的错误日志分析了下，是和网络有关
