### ISSUE TITLE
请配置PandoraNext相关环境变量

### ISSUE THREAD

**Issue by dqzboy** [nianhua99/PandoraNext-Helper#8]
2023-12-23 16:56:38.682 | ERROR    | app:check_require_config:105 - 请配置PandoraNext相关环境变量
2023-12-23 16:56:39.376 | ERROR    | app:check_require_config:105 - 请配置PandoraNext相关环境变量
2023-12-23 16:56:40.214 | ERROR    | app:check_require_config:105 - 请配置PandoraNext相关环境变量
2023-12-23 16:56:41.226 | ERROR    | app:check_require_config:105 - 请配置PandoraNext相关环境变量
2023-12-23 16:56:42.630 | ERROR    | app:check_require_config:105 - 请配置PandoraNext相关环境变量

大佬，我这边启动一直提示这个，但是我已经按照[README.配置了

**Comment by dqzboy** [comment]
我的启动命令如下：
```shell
docker run -d --restart=always --name PandoraNext-Helper --net=bridge \
    -p 8182:8182 \
    -v /data/pandora-next:/data \
    -e PANDORA_NEXT_DOMAIN:http://10.11.21.7:8181 \
    q11391/pandora-next-helper
```

**Comment by nianhua99** [comment]
-e PANDORA_NEXT_DOMAIN:http://10.11.21.7:8181 \
 这一行改成
 -e PANDORA_NEXT_DOMAIN="http://10.11.21.7:8181" \
试一下，文档有问题，我去改一下，不好意思，感谢指正

**Comment by dqzboy** [comment]
我找到问题了，不是这个问题，是那个配置PandoraNext的路径，必须是config.json所在目录的上一级才行

**Comment by dqzboy** [comment]
然后现在我遇到这个问题：ERROR    | app:check_require_config:127 - setup_password强度不符合要求，请重新配置

**Comment by dqzboy** [comment]
> -e PANDORA_NEXT_DOMAIN:http://10.11.21.7:8181 这一行改成 -e PANDORA_NEXT_DOMAIN="http://10.11.21.7:8181" 试一下，文档有问题，我去改一下，不好意思，感谢指正

确实这个也不对

**Comment by nianhua99** [comment]
> 然后现在我遇到这个问题：ERROR | app:check_require_config:127 - setup_password强度不符合要求，请重新配置

这个当前helper 的要求是 字母+数字+符号，比pandoranext严格了一些，下个版本会恢复为字母+数字，和pandoranext保持一致，你可以先改一改setup_password

**Comment by dqzboy** [comment]
> > 然后现在我遇到这个问题：ERROR | app:check_require_config:127 - setup_password强度不符合要求，请重新配置
> 
> 这个当前helper 的要求是 字母+数字+符号，比pandoranext严格了一些，下个版本会恢复为字母+数字，和pandoranext保持一致，你可以先改一改setup_password

docker启动的话  如何修改，传环境变量吗？

**Comment by nianhua99** [comment]
> > > 然后现在我遇到这个问题：ERROR | app:check_require_config:127 - setup_password强度不符合要求，请重新配置
> > 
> > 
> > 这个当前helper 的要求是 字母+数字+符号，比pandoranext严格了一些，下个版本会恢复为字母+数字，和pandoranext保持一致，你可以先改一改setup_password
> 
> docker启动的话 如何修改，传环境变量吗？

就改你pandoranext 的config.json

**Comment by dqzboy** [comment]
现在提示ERROR    | app:check_require_config:141 - 不支持的验证码提供商

**Comment by dqzboy** [comment]
我使用的是pandora-next默认的配置，都是为空的，那么咱这个项目就无法启动

**Comment by nianhua99** [comment]
> 我使用的是pandora-next默认的配置，都是为空的，那么咱这个项目就无法启动

是的，setup_password|captcha|proxy_api_prefix 都是必选的

**Comment by dqzboy** [comment]
> > 我使用的是pandora-next默认的配置，都是为空的，那么咱这个项目就无法启动
> 
> 是的，setup_password|captcha|proxy_api_prefix 都是必选的

下个版本可以允许这3个参数为空吗？

**Comment by nianhua99** [comment]
> > > 我使用的是pandora-next默认的配置，都是为空的，那么咱这个项目就无法启动
> > 
> > 
> > 是的，setup_password|captcha|proxy_api_prefix 都是必选的
> 
> 下个版本可以允许这3个参数为空吗？

没有计划，不太安全

**Comment by dqzboy** [comment]
> > > > 我使用的是pandora-next默认的配置，都是为空的，那么咱这个项目就无法启动
> > > 
> > > 
> > > 是的，setup_password|captcha|proxy_api_prefix 都是必选的
> > 
> > 
> > 下个版本可以允许这3个参数为空吗？
> 
> 没有计划，不太安全

对于像我这种自己用，其实确实不需要搞那么复杂的验证

**Comment by nianhua99** [comment]
> > > > > 我使用的是pandora-next默认的配置，都是为空的，那么咱这个项目就无法启动
> > > > 
> > > > 
> > > > 是的，setup_password|captcha|proxy_api_prefix 都是必选的
> > > 
> > > 
> > > 下个版本可以允许这3个参数为空吗？
> > 
> > 
> > 没有计划，不太安全
> 
> 对于像我这种自己用，其实确实不需要搞那么复杂的验证

因为肯定是开放到外网的，实在嫌麻烦可以用测试的 hcaptcha key，你可以在hcaptcha的官网文档里看到，那个不用打码 直接pass，但是你要考虑清楚安全因素
