### ISSUE TITLE
建议在“添加新乘客”时提供shared属性

### ISSUE THREAD

**Issue by hiBlunt** [nianhua99/PandoraNext-Helper#9]
![image](https://github.com/nianhua99/PandoraNext-Helper/assets/21240907/bcaa2db2-5266-4023-b790-e4d8f015b9dc)
如图，在“添加新乘客”时无法指定shared属性，导致同步到pandora next的tokens.json后，token key的值中不含“shared”，进一步导致pandora next无法使用token key作为用户名登录。

**Comment by nianhua99** [comment]
添加乘客就是生成Share Token，PandoraNext针对ShareToken只有两种登录方式，一种是Tokenkey（UniqueName） + Password登录，另一种是直接使用Share Token（fk开头的token串），这两种方式都不允许 shared = true，也就是说，ShareToken不能用在你的分享页中，如下图
![image](https://github.com/nianhua99/PandoraNext-Helper/assets/48168645/5c4249f3-756c-4579-8a3c-8fd3fc5250de)

**Comment by hiBlunt** [comment]
感谢。找到无法使用密码登录的真正原因了，helper上点击“同步至PandoraNext”后，还需要在pandora的/setup中点击“保存并热加载”。请问是否有办法同步之后自动热加载？

**Comment by nianhua99** [comment]
已修复
